version: '3.8'

x-common-variables: &common-variables
  MYSQL_DATABASE: cnab
  MYSQL_USER: MYSQL_USER
  MYSQL_PASSWORD: MYSQL_PASSWORD

services:

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    volumes:
      - ./backend/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
     - "3307:3306"
    networks:
      - cnab-app
    environment:
      <<: *common-variables
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: cnab
      MYSQL_HOST: localhost

  frontend:
    image: nginx
    container_name: frontend
    volumes:
      - ./frontend/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html
    ports:
      - 80:80

  backend:
    image: node
    container_name: backend
    restart: always
    volumes:
      - ./backend:/backend
    ports:
      - 3333:3333
    depends_on:
      - mysql
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql
    command: bash -c "cd /backend && npm i && node index.js"
    links:
      - mysql
    networks:
      - cnab-app

networks:
  cnab-app:
    driver: bridge
